default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: nimmToEat_development
   host: localhost
   username: rubyuser
   password: 12345

test:
   adapter: postgresql
   encoding: unicode
   database: nimmToEat_test
   host: localhost
   username: rubyuser
   password: 12345
 
production:
   adapter: postgresql
   encoding: unicode
   database: nimmToEat_production
   host: localhost
   username: rubyuser
   password: 12345
